import type { Node } from "../../../lib/ReactFlow";

const nodes: Node[] = [
  {
    id: "registers-bank",
    data: {
      labelKey: "registersBank.label",
      width: 400,
      height: 200,
      controlBusBitLoad: {
        label: "REGCAR",
        controlBusBitPosition: 22,
      },
      controlBusBitRelease: {
        label: "REGBUS",
        controlBusBitPosition: 21,
        targetId: "databus",
      },
      handlePos: ["bottom-target-30", "bottom-source-70"],
    },
    draggable: false,
    position: { x: -440, y: -759 },
    className: "light",
    type: "loadableNode",
    isParent: true,
  },
  {
    id: "rb",
    position: { x: 20, y: 50 },
    parentNode: "registers-bank",
    draggable: false,
    type: "registerNode",
    data: {
      labelKey: "rb.label",
      readOnly: true,
      getFunction: "get_register_b",
      helpInfoKey: "rb.helpInfo",
    },
  },
  {
    id: "rc",
    position: { x: 200, y: 50 },
    parentNode: "registers-bank",
    draggable: false,
    type: "registerNode",
    data: {
      labelKey: "rc.label",
      readOnly: true,
      getFunction: "get_register_c",
      helpInfoKey: "rc.helpInfo",
    },
  },
  {
    id: "rd",
    position: { x: 20, y: 120 },
    parentNode: "registers-bank",
    draggable: false,
    type: "registerNode",
    data: {
      labelKey: "rd.label",
      readOnly: true,
      getFunction: "get_register_d",
      helpInfoKey: "rd.helpInfo",
    },
  },
  {
    id: "re",
    position: { x: 203, y: 115 },
    parentNode: "registers-bank",
    draggable: false,
    type: "registerNode",
    data: {
      labelKey: "re.label",
      readOnly: true,
      getFunction: "get_register_e",
      helpInfoKey: "re.helpInfo",
    },
  },

  {
    id: "acum",
    position: { x: -1, y: -590 },
    draggable: false,
    type: "registerNode",
    data: {
      labelKey: "acum.label",
      // handlePos: ["bottom", "top"],
      handlePos: ["bottom-target-30", "bottom-source-70", "top-source-50"],
      handlesCount: 2,
      readOnly: true,
      width: 70,
      height: 63,
      controlBusBitLoad: {
        label: "ACCAR",
        controlBusBitPosition: 2,
      },
      controlBusBitRelease: {
        label: "ACBUS",
        controlBusBitPosition: 1,
        targetId: "databus",
      },
      getFunction: "get_register_acum",
      helpInfoKey: "acum.helpInfo",
    },
  },

  {
    id: "2op",
    position: { x: 185, y: -590 },
    draggable: false,
    type: "registerNode",
    data: {
      labelKey: "2op.label",
      handlePos: ["bottom-target-50", "top-source-50"],
      readOnly: true,
      width: 70,
      height: 63,
      controlBusBitLoad: {
        label: "2OPCAR",
        controlBusBitPosition: 15,
      },
      getFunction: "get_register_2op",
    },
  },
  {
    id: "pc",
    position: { x: -845.9999999999999, y: -360 },
    draggable: false,
    type: "registerNode",
    data: {
      labelKey: "pc.label",
      readOnly: true,
      handlePos: ["top-target-50", "bottom-source-50", "bottom-target-25"],
      // handlesCount: 1,
      width: 70,
      height: 63,
      controlBusBitLoad: {
        label: "PCCAR",
        controlBusBitPosition: 16,
      },
      getFunction: "get_register_pc",
      helpInfoKey: "pc.helpInfo",
    },
  },

  {
    id: "sp",
    position: { x: -669, y: -358 },
    draggable: false,
    type: "registerNode",
    data: {
      labelKey: "sp.label",
      handlePos: ["top-target-50", "bottom-source-50"],
      readOnly: true,
      width: 70,
      height: 63,
      controlBusBitLoad: {
        label: "SPCAR",
        controlBusBitPosition: 29,
      },
      getFunction: "get_register_sp",
      helpInfoKey: "sp.helpInfo",
    },
  },
  {
    id: "h",
    position: { x: -494, y: -358 },
    draggable: false,
    type: "registerNode",
    data: {
      labelKey: "h.label",
      handlePos: ["top-target-50", "bottom-source-100"],
      readOnly: true,
      width: 70,
      height: 63,
      controlBusBitLoad: {
        label: "HCAR",
        controlBusBitPosition: 6,
      },
      getFunction: "get_register_h",
    },
  },
  {
    id: "l",
    position: { x: -329, y: -358.00000000000006 },
    draggable: false,
    type: "registerNode",
    data: {
      labelKey: "l.label",
      handlePos: ["top-target-50"],
      readOnly: true,
      width: 70,
      height: 63,
      controlBusBitLoad: {
        label: "LCAR",
        controlBusBitPosition: 10,
      },
      getFunction: "get_register_l",
    },
  },

  {
    id: "8",
    data: {
      labelKey: "controlunit.label",
      width: 400,
      height: 120,
    },
    draggable: false,
    position: { x: -883, y: -679 },
    className: "light",
    type: "loadableNode",
    isParent: true,
  },

  {
    id: "ri",
    position: { x: 20, y: 40 },
    parentNode: "8",
    draggable: false,
    type: "registerNode",
    data: {
      labelKey: "ri.label",
      readOnly: true,
      width: 70,
      height: 63,
      handlesCount: 1,
      controlBusBitLoad: {
        label: "RICAR",
        controlBusBitPosition: 34,
      },
      getFunction: "get_register_ri",
      helpInfoKey: "ri.helpInfo",
      handlePos: [
        "bottom-target-60",
        "bottom-source-10",
        "bottom-source-20",
      ],
    },
  },
  {
    id: "8b",
    position: { x: 200, y: 40 },
    parentNode: "8",
    draggable: false,
    type: "registerNode",
    data: {
      labelKey: "state.label",
      readOnly: true,
      width: 70,
      height: 63,
      getFunction: "get_state",
    },
  },
  {
    id: "memory",
    position: { x: 26, y: -234 },
    type: "memoryNode",
    draggable: false,
    data: {
      labelKey: "memory.label",
      readOnly: false,
      handlePos: ["left-target-50", "top-target-30", "top-source-73"],
      controlBusBitRelease: {
        label: "MEMBUS",
        controlBusBitPosition: 12,
        targetId: "databus",
      },
      width: 300,
      helpInfoKey: "memory.helpInfo",
    },
  },
  {
    id: "transition-state",
    position: { x: -1174, y: -430 },
    type: "stateTransition",
    data: {
      labelKey: "transitionstate.label",
    },
    draggable: false,
  },
  {
    id: "debugger",
    position: { x: -1159, y: -706 },
    type: "debuggerNode",
    data: {
      labelKey: "debugger.label",
    },
    draggable: false,
  },
  {
    id: "flags",
    position: { x: 349, y: -739 },
    draggable: false,
    type: "flagsNode",
    data: {
      labelKey: "flags.label",
      helpInfoKey: "flags.helpInfo",
      fzHelpInfoKey: "flags.fzHelpInfo",
      fcHelpInfoKey: "flags.fcHelpInfo",
    },
  },
  {
    id: "clockCycleTime",
    position: { x: -1120, y: -226 },
    draggable: false,
    type: "cycleTimeNode",
    data: {
      labelKey: "clockCycleTime.label",
    },
  },
  {
    id: "alu",
    position: { x: 61.99999999999997, y: -741 },
    draggable: false,
    type: "aluNode",
    data: {
      labelKey: "alu.label",
      handlePos: ["left-source-50"],
      controlBusBitRelease: {
        label: "ALUBUS",
        controlBusBitPosition: 3,
        targetId: "databus",
      },
    },
  },
  {
    id: "databus",
    position: { x: -842, y: -468 },
    draggable: false,
    type: "busNode",
    data: {
      labelKey: "databus.label",
      width: 1200,
      getFunction: "get_data_bus",
    },
  },
  {
    id: "automata",
    position: { x: 455.9999999999999, y: -696 },
    draggable: false,
    type: "automataNode",
    data: {
      labelKey: "automata.label",
      width: 400,
      height: 500,
    },
  },
  {
    id: "mx",
    position: { x: -271, y: -274 },
    draggable: false,
    type: "mxNode",
    data: {
      labelKey: "mx.label",
      width: 220,
      height: 240,
      handlePos: ["top-target-10", "top-source-5"],
    },
  },
  {
    id: "inc",
    position: { x: -63, y: -5 },
    draggable: false,
    type: "incNode",
    data: {
      "labelKey": "inc.label",
      "width": 60,
      "height": 60
    },
  },
];
export default nodes;
